AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Event consumer service
Globals:
  Function:
    Runtime: python3.8
Parameters:
  DiscordClientId:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Honeycomb API Key
    Default: /discobot/discord_client_id
  DiscordPublicKey:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Usage Plan API Key
    Default: /discobot/discord_public_key
  HoneycombApiKey:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Honeycomb API Key
    Default: /discobot/honeycomb_api_key
  UsagePlanApiKey:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Usage Plan API Key
    Default: /discobot/usage_plan_api_key
Resources:
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Description: Key used to post events to the API.
      Enabled: true
      StageKeys:
      - RestApiId:
          Ref: SlashCommandsApi
        StageName:
          Ref: SlashCommandsApi.Stage
  ApiUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId:
        Ref: ApiKey
      KeyType: API_KEY
      UsagePlanId:
        Ref: ApiUsagePlan
  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
      - ApiId:
          Ref: SlashCommandsApi
        Stage:
          Ref: SlashCommandsApi.Stage
      Quota:
        Limit: 16000
        Period: DAY
      Throttle:
        BurstLimit: 10
        RateLimit: 10
  SlashCommandsApi:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration: REGIONAL
      StageName: Prod
      DefinitionBody:
        swagger: 2.0
        x-amazon-apigateway-request-validators:
          params:
            validateRequestBody: false
            validateRequestParameters: true
        paths:
          /discord:
            post:
              x-amazon-apigateway-request-validator: params
              parameters:
              - in: header
                required: true
                type: string
                name: X-Signature-Ed25519
              - in: header
                required: true
                type: integer
                name: X-Signature-Timestamp
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${EventReceiver.Arn}/invocations
  EventReceiver:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://anjou-sl-resources/582f9298762f925a020106a0b289c9ca
      Handler: slash_command.lambda_handler
      Timeout: 30
      Environment:
        Variables:
          DISCORD_CLIENT_ID:
            Ref: DiscordClientId
          DISCORD_PUBLIC_KEY:
            Ref: DiscordPublicKey
          HONEYCOMB_API_KEY:
            Ref: HoneycombApiKey
      Events:
        Interaction:
          Type: Api
          Properties:
            Path: /discord
            Method: POST
            RestApiId:
              Ref: SlashCommandsApi
Outputs:
  ApiKeyId:
    Value:
      Ref: ApiKey
  ApiUrl:
    Value:
      Fn::Sub: ${SlashCommandsApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${SlashCommandsApi.Stage}
